[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
